### ISSUE TITLE
Run full system

### ISSUE THREAD

**Issue by ZhangMeng-program** [esl-epfl/gem5-X#1]
First, I compile the ARM_MOESI_hammer with the command line
scons build/ARM_MOESI_hammer/gem5.opt -j 7

Then I configure the full system according to the Manual.

Next I run the command line as following:
build/ARM_MOESI_hammer/gem5.opt --remote-gdb-port=0 configs/example/fs.py \
--cpu-clock=1GHz --kernel=vmlinux --machine-type=VExpress_GEM5_V1 \
--dtb-file=/home/gem5/gem5/system/arm/dt/armv8_gem5_v1_1cpu.dtb \
--disk-image=gem5_ubuntu16.img --caches --l2cache --l1i_size=32kB \
--l1d_size=32kB --l2_size=1MB --l2_assoc=2 --mem-type=DDR4_2400_4x16 \
--mem-ranks=4 --mem-size=4GB --sys-clock=1600MHz \
--ruby --network=garnet2.0 --cpu-type=O3CPU

But I encounter some strange issues:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/ARM_MESI_Three_Level/python/m5/main.py", line 457, in main
    exec(filecode, scope)
  File "configs/example/fs.py", line 308, in <module>
    (options, args) = parser.parse_args()
  File "/usr/lib/python2.7/optparse.py", line 1384, in parse_args
    values = self.get_default_values()
  File "/usr/lib/python2.7/optparse.py", line 1329, in get_default_values
    defaults[option.dest] = option.check_value(opt_str, default)
  File "/usr/lib/python2.7/optparse.py", line 770, in check_value
    return checker(self, opt, value)
  File "/usr/lib/python2.7/optparse.py", line 439, in check_choice
    % (opt, value, choices))
optparse.OptionValueError: option --cpu-type: invalid choice: 'AtomicSimpleCPU' (choose from 'O3_ARM_v7a_3', 'TimingSimpleCPU', 'ex5_big', 'DerivO3CPU', 'TraceCPU')

I find in the build_opts folder, the ARM_MOESI_hammer specifies the CPU_MODELLS=
'TimingSimpleCPU, O3CPU', so in the command line I specify the cpu-type=O3CPU
And I also try to change the cpu-type parameter as the options in the error information, but it seems that my operation does not work.
To be honest, I did not understand what to happen and why. Or the gem5-X did not support using ruby and garnet2.0 .
And how can I solve this problem?
If I use the ARM to replace the ARM_MOESI_hammer, the full system can work normally.
But I need to add the ruby and network?
Are there any suggestions?
Thanks a lot!

**Comment by yasirmahmoodqureshi** [comment]
Gem5-X is not tested for ruby and garnet2.0 with ARM system yet.
